using Aqevryn.Common;
using System.Text.Json;

namespace Aqevryn.Api;

/// <summary>
/// Generates a standalone public research publication website.
/// Creates clean, professional HTML pages for all concluded research.
/// Designed to be served at agents.aqevryn.me
/// </summary>
public class PublicSite
{
    private readonly string _outputDir;

    public PublicSite(string outputDir = "public-site")
    {
        _outputDir = outputDir;
    }

    public void Generate()
    {
        Directory.CreateDirectory(_outputDir);
        Directory.CreateDirectory(Path.Combine(_outputDir, "research"));

        var completed = CompletedResearchRegistry.GetAll();
        GenerateIndex(completed);
        foreach (var r in completed)
            GenerateResearchPage(r);

        GenerateAboutPage();
        GenerateMethodologyPage();
        GenerateStyle();
        
        Console.WriteLine($"📄 Public site generated: {_outputDir}/ — {completed.Count} research papers");
    }

    private void GenerateIndex(List<CompletedResearch> research)
    {
        var cards = string.Join("\n", research.Select(r => $@"
        <article class=""card"">
            <h2><a href=""/research/{Slugify(r.Topic)}.html"">{r.Topic}</a></h2>
            <div class=""meta"">
                <span>Score: {r.EditorialScore}/100</span>
                <span>{r.ArticleCount} sources</span>
                <span>{r.FindingCount} findings</span>
                <time>{r.CompletedAt:yyyy-MM-dd}</time>
            </div>
            <p>{r.ResearchQuestion}</p>
        </article>"));

        var html = $@"<!DOCTYPE html>
<html lang=""en"">
<head>
    <meta charset=""UTF-8"">
    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">
    <title>Aqevryn Research</title>
    <link rel=""stylesheet"" href=""/style.css"">
</head>
<body>
    <header>
        <h1>Aqevryn Research</h1>
        <nav>
            <a href=""/"">Home</a>
            <a href=""/about"">About</a>
            <a href=""/methodology"">Methodology</a>
        </nav>
    </header>
    <main>
        <section class=""hero"">
            <h1>Research Publications</h1>
            <p>Autonomous technology research — evidence-based, transparent, rigorous.</p>
        </section>
        <section>
            {(research.Count > 0 ? cards : "<p>No research published yet.</p>")}
        </section>
    </main>
    <footer>
        <p>Generated by <a href=""https://github.com/aqevryn-cloud/aqevryn"">Aqevryn</a></p>
    </footer>
</body>
</html>";

        File.WriteAllText(Path.Combine(_outputDir, "index.html"), html);
    }

    private void GenerateResearchPage(CompletedResearch r)
    {
        var slug = Slugify(r.Topic);
        var html = $@"<!DOCTYPE html>
<html lang=""en"">
<head>
    <meta charset=""UTF-8"">
    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">
    <title>{r.Topic} — Aqevryn Research</title>
    <link rel=""stylesheet"" href=""/style.css"">
</head>
<body>
    <header>
        <h1><a href=""/"" style=""color:inherit;text-decoration:none"">Aqevryn Research</a></h1>
        <nav>
            <a href=""/"">Home</a>
            <a href=""/about"">About</a>
            <a href=""/methodology"">Methodology</a>
        </nav>
    </header>
    <main>
        <article class=""research"">
            <h1>{r.Topic}</h1>
            <div class=""meta"">
                <span>Editorial Score: {r.EditorialScore}/100</span>
                <span>{r.ArticleCount} articles analyzed</span>
                <span>{r.FindingCount} findings extracted</span>
                <time>{r.CompletedAt:yyyy-MM-dd}</time>
            </div>
            <h2>Research Question</h2>
            <p>{r.ResearchQuestion}</p>
            {(r.ArticleTitle != null ? $"<h2>Article</h2>\n<p><em>{r.ArticleTitle}</em></p>" : "")}
            {(r.PrUrl != null ? $"<p><a href='{r.PrUrl}'>View on GitHub</a></p>" : "")}
            <div class=""metadata"">
                <h2>Metadata</h2>
                <ul>
                    <li>Final Score: {r.FinalScore}</li>
                    <li>Editorial Score: {r.EditorialScore}/100</li>
                    <li>Sources Analyzed: {r.ArticleCount}</li>
                    <li>Findings: {r.FindingCount}</li>
                    <li>Completed: {r.CompletedAt:yyyy-MM-dd}</li>
                </ul>
            </div>
        </article>
    </main>
    <footer>
        <p>Generated by <a href=""https://github.com/aqevryn-cloud/aqevryn"">Aqevryn</a></p>
    </footer>
</body>
</html>";

        File.WriteAllText(Path.Combine(_outputDir, "research", $"{slug}.html"), html);
    }

    private void GenerateAboutPage()
    {
        File.WriteAllText(Path.Combine(_outputDir, "about.html"), @"<!DOCTYPE html>
<html lang=""en"">
<head>
<meta charset=""UTF-8"">
<meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">
<title>About — Aqevryn Research</title>
<link rel=""stylesheet"" href=""/style.css"">
</head>
<body>
<header><h1><a href=""/"" style=""color:inherit;text-decoration:none"">Aqevryn Research</a></h1>
<nav><a href=""/"">Home</a><a href=""/about"">About</a><a href=""/methodology"">Methodology</a></nav></header>
<main>
<h1>About Aqevryn</h1>
<p>Aqevryn is an autonomous technology research and intelligence organization.</p>
<p>It continuously discovers emerging technology developments, evaluates their significance, conducts evidence-based research, and publishes original findings.</p>
<p>The system prioritizes research quality over publication volume.</p>
</main>
<footer><p>Generated by Aqevryn</p></footer>
</body>
</html>");
    }

    private void GenerateMethodologyPage()
    {
        File.WriteAllText(Path.Combine(_outputDir, "methodology.html"), @"<!DOCTYPE html>
<html lang=""en"">
<head>
<meta charset=""UTF-8"">
<meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">
<title>Methodology — Aqevryn Research</title>
<link rel=""stylesheet"" href=""/style.css"">
</head>
<body>
<header><h1><a href=""/"" style=""color:inherit;text-decoration:none"">Aqevryn Research</a></h1>
<nav><a href=""/"">Home</a><a href=""/about"">About</a><a href=""/methodology"">Methodology</a></nav></header>
<main>
<h1>Research Methodology</h1>
<h2>How Topics Are Discovered</h2>
<p>Topics are discovered through keyword-based extraction from collected articles across 16 technology categories, combined with LLM-based refinement.</p>
<h2>How Sources Are Evaluated</h2>
<p>Sources are classified by type with reliability scores: research papers (1.0), documentation (0.95), engineering blogs (0.90), publications (0.85), reports (0.80), community (0.55).</p>
<h2>How Topics Are Scored</h2>
<p>Topics are scored across five dimensions: Trend Score (25%), Researchability (25%), Market Viability (20%), Novelty (15%), Technical Significance (15%).</p>
<h2>How Research Is Performed</h2>
<p>Research uses a multi-stage pipeline: planning, source retrieval, evidence extraction, LLM-enhanced analysis, and conclusion formation.</p>
<h2>How Citations Are Validated</h2>
<p>Every claim is validated against its source. The system checks for source URL validity and detects potentially fabricated statistics.</p>
</main>
<footer><p>Generated by Aqevryn</p></footer>
</body>
</html>");
    }

    private void GenerateStyle()
    {
        File.WriteAllText(Path.Combine(_outputDir, "style.css"), @"*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;font-size:16px;line-height:1.6;color:#1f2328;max-width:800px;margin:0 auto;padding:20px}
header{border-bottom:1px solid #d0d7de;padding:20px 0;margin-bottom:20px}
header h1{font-size:1.4em}
header nav a{color:#0969da;text-decoration:none;margin-right:16px}
header nav a:hover{text-decoration:underline}
h1{font-size:1.8em;margin-bottom:16px}
h2{font-size:1.4em;margin:24px 0 12px;border-bottom:1px solid #d0d7de;padding-bottom:8px}
p{margin-bottom:16px}
.hero{padding:40px 0;text-align:center}
.hero h1{font-size:2.4em}
.hero p{font-size:1.2em;color:#656d76}
.card{padding:20px;border:1px solid #d0d7de;border-radius:6px;margin-bottom:16px}
.card h2{margin:0 0 8px 0;border:none}
.card h2 a{color:#1f2328;text-decoration:none}
.card h2 a:hover{color:#0969da}
.card .meta{color:#656d76;font-size:0.9em;margin-bottom:8px}
.card .meta span{margin-right:16px}
.card p{color:#656d76}
.research .meta{color:#656d76;font-size:0.9em;margin-bottom:24px}
.research .meta span{margin-right:16px}
.metadata{background:#f6f8fa;padding:20px;border-radius:6px;margin-top:24px}
footer{border-top:1px solid #d0d7de;padding:20px 0;margin-top:40px;color:#656d76;font-size:0.9em}
@media(max-width:600px){body{padding:12px}h1{font-size:1.4em}}");
    }

    private static string Slugify(string text)
    {
        var slug = text.ToLower().Replace(" ", "-").Replace("/", "-");
        slug = System.Text.RegularExpressions.Regex.Replace(slug, @"[^a-z0-9-]", "");
        return slug.Trim('-')[..Math.Min(slug.Length, 60)];
    }
}